# -*- coding: utf-8 -*-
"""Dataset loading, feature selection, and train/test preprocessing."""

import os
from dataclasses import dataclass
from typing import Optional

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

from src.core import config
from src.core.utils import load_csv, logger

DEFAULT_THRESHOLD = 0.40
TARGET_RECALL = 0.85
USE_LAGGED_LABEL = True
LEAKAGE_FEATURES = {
    "ebit_to_interest",
    "icr",
    "current_ratio",
    "total_equity",
    "springate_distressed",
    "zmijewski_distressed",
}


@dataclass
class PreparedDataset:
    df: pd.DataFrame
    feature_cols: list
    target_col: str
    split_year: int
    train_years: np.ndarray
    X_train_scaled: pd.DataFrame
    X_test_scaled: pd.DataFrame
    y_train: pd.Series
    y_test: pd.Series
    scaler: StandardScaler
    scale_pos_weight: float


def prepare_train_test_split(split_year: int = 2022) -> Optional[PreparedDataset]:
    """Load dataset, build features, and return scaled train/test matrices."""
    from src.core.database import SessionLocal, CompanyDistressAnalysis
    db = SessionLocal()
    try:
        query = db.query(CompanyDistressAnalysis)
        df = pd.read_sql(query.statement, db.bind)
    except Exception as e:
        logger.error(f"❌ Failed to load dataset from SQLite: {e}")
        return None
    finally:
        db.close()

    if df.empty:
        logger.error("❌ Final training dataset in SQLite is empty!")
        return None
    
    # Remove autogenerated id and systemic_contagion_prob fields so they are not used as features
    if "id" in df.columns:
        df.drop(columns=["id"], inplace=True)
    
    # ------------------------------------------------------------------
    # LAGGED LABEL MODE: load _lagged dataset for proper T → T+1 setup
    # ------------------------------------------------------------------
    if USE_LAGGED_LABEL:
        df = df[df["distress_label_next_year"].notna()].copy()
        df["distress_label_next_year"] = df["distress_label_next_year"].astype(int)
        target_col = "distress_label_next_year"
        logger.info("✅ LAGGED MODE: features(T) → distress_label(T+1) from SQLite — No data leakage")
    else:
        target_col = "distress_label"
        logger.info("⚠️ SAME-YEAR MODE: features(T) → distress_label(T) from SQLite — Data leakage present")
        
    # Ensure year column is treated as integer
    df["year"] = df["year"].astype(int)
    
    train_mask = df["year"] <= split_year
    test_mask = df["year"] > split_year
    
    # Define features and target
    exclude_cols = {"ticker", "company_name", "year", "exchange", "industry",
                    "distress_label", "distress_label_next_year", "distress_probability", 
                    "systemic_contagion_prob", "last_updated"}
    if USE_LAGGED_LABEL:
        exclude_cols |= LEAKAGE_FEATURES
        logger.info(f"🚫 Excluded {len(LEAKAGE_FEATURES)} leakage features: {sorted(LEAKAGE_FEATURES)}")
    feature_cols = [col for col in df.columns if col not in exclude_cols]
    
    X_train = df.loc[train_mask, feature_cols]
    y_train = df.loc[train_mask, target_col]
    train_years = df.loc[train_mask, "year"].to_numpy()
    
    X_test = df.loc[test_mask, feature_cols]
    y_test = df.loc[test_mask, target_col]
    
    logger.info(f"📊 Dataset successfully prepared:")
    logger.info(f"   * Total unique features      : {len(feature_cols)}")
    logger.info(f"   * Train Set (Years <= {split_year}): {len(X_train)} records")
    logger.info(f"   * Test Set (Years > {split_year}) : {len(X_test)} records")
    
    distress_rate_train = np.mean(y_train)
    distress_rate_test = np.mean(y_test)
    logger.info(f"   * Distress Rate in Train Set : {distress_rate_train:.2%}")
    logger.info(f"   * Distress Rate in Test Set  : {distress_rate_test:.2%}")
    
    if len(X_train) == 0 or len(X_test) == 0:
        logger.error("❌ Not enough records in Train or Test set! Make sure data spans multiple years.")
        return None

    scaler = StandardScaler()
    X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train), columns=feature_cols)
    X_test_scaled = pd.DataFrame(scaler.transform(X_test), columns=feature_cols)

    use_smote = os.getenv("FINVISTA_USE_SMOTE", "0") == "1"
    if use_smote:
        logger.info("⚖️ Applying SMOTE + Tomek Links to balance and clean the training set...")
        X_train_scaled, y_train, train_years = smote_tomek(
            X_train_scaled, y_train, train_years, target_ratio=1.0, random_state=42
        )
        neg_count = np.sum(y_train == 0)
        pos_count = np.sum(y_train == 1)
        logger.info(f"   * Resampled & Cleaned Train Set: {len(X_train_scaled)} records")
        logger.info(f"   * Resampled Class Counts: 0={neg_count}, 1={pos_count}")
    else:
        neg_count = np.sum(y_train == 0)
        pos_count = np.sum(y_train == 1)

    scale_pos_weight = neg_count / pos_count if pos_count > 0 else 1.0
    logger.info(f"⚖️ Calculated Class Balance Factor: {scale_pos_weight:.2f}")

    return PreparedDataset(
        df=df,
        feature_cols=feature_cols,
        target_col=target_col,
        split_year=split_year,
        train_years=train_years,
        X_train_scaled=X_train_scaled,
        X_test_scaled=X_test_scaled,
        y_train=y_train,
        y_test=y_test,
        scaler=scaler,
        scale_pos_weight=scale_pos_weight,
    )


def simple_smote(X, y, groups, target_ratio=1.0, k_neighbors=5, random_state=42):
    """
    A lightweight, pure-Python implementation of SMOTE (Synthetic Minority Over-sampling Technique)
    which also correctly handles groups (like train_years) for cross-validation compatibility.
    """
    from sklearn.neighbors import NearestNeighbors
    np.random.seed(random_state)
    
    # Convert inputs to numpy arrays for reliable indexing
    X_arr = np.array(X)
    y_arr = np.array(y)
    groups_arr = np.array(groups)
    
    classes, counts = np.unique(y_arr, return_counts=True)
    if len(classes) != 2:
        return X_arr, y_arr, groups_arr
        
    minority_class = classes[np.argmin(counts)]
    
    minority_indices = np.where(y_arr == minority_class)[0]
    num_minority = len(minority_indices)
    num_majority = len(y_arr) - num_minority
    
    target_minority = int(num_majority * target_ratio)
    num_synthetic = target_minority - num_minority
    
    if num_synthetic <= 0:
        return X_arr, y_arr, groups_arr
        
    X_min = X_arr[minority_indices]
    groups_min = groups_arr[minority_indices]
    
    nn = NearestNeighbors(n_neighbors=min(k_neighbors + 1, num_minority), algorithm='auto')
    nn.fit(X_min)
    neighbors = nn.kneighbors(X_min, return_distance=False)
    
    synthetic_samples = []
    synthetic_groups = []
    
    for _ in range(num_synthetic):
        idx = np.random.choice(num_minority)
        neighbor_idx = np.random.choice(neighbors[idx][1:])
        
        diff = X_min[neighbor_idx] - X_min[idx]
        gap = np.random.rand()
        synthetic_sample = X_min[idx] + gap * diff
        synthetic_samples.append(synthetic_sample)
        
        # Inherit the group (year) from the base minority sample
        synthetic_groups.append(groups_min[idx])
        
    X_syn = np.vstack(synthetic_samples)
    y_syn = np.full(num_synthetic, minority_class)
    groups_syn = np.array(synthetic_groups)
    
    X_resampled = np.vstack([X_arr, X_syn])
    y_resampled = np.concatenate([y_arr, y_syn])
    groups_resampled = np.concatenate([groups_arr, groups_syn])
    
    # Convert back to pandas if the inputs were pandas objects, to maintain types
    if isinstance(X, pd.DataFrame):
        X_resampled = pd.DataFrame(X_resampled, columns=X.columns)
    if isinstance(y, pd.Series):
        y_resampled = pd.Series(y_resampled, name=y.name)
        
    return X_resampled, y_resampled, groups_resampled


def remove_tomek_links(X, y, groups=None):
    """
    Finds and removes Tomek Links from the dataset (X, y).
    A Tomek Link is a pair of nearest neighbors (A, B) of different classes.
    Removing them cleans the decision boundary.
    """
    from sklearn.neighbors import NearestNeighbors
    X_arr = np.array(X)
    y_arr = np.array(y)
    
    n_samples = len(X_arr)
    if n_samples < 2:
        if groups is not None:
            return X, y, groups
        return X, y
        
    nn = NearestNeighbors(n_neighbors=2)
    nn.fit(X_arr)
    distances, indices = nn.kneighbors(X_arr)
    
    tomek_indices = set()
    for i in range(n_samples):
        nn_idx = indices[i, 1]
        if y_arr[i] != y_arr[nn_idx]:
            if indices[nn_idx, 1] == i:
                tomek_indices.add(i)
                tomek_indices.add(nn_idx)
                
    keep_mask = np.ones(n_samples, dtype=bool)
    for idx in tomek_indices:
        keep_mask[idx] = False
        
    X_cleaned = X_arr[keep_mask]
    y_cleaned = y_arr[keep_mask]
    
    if isinstance(X, pd.DataFrame):
        X_cleaned = pd.DataFrame(X_cleaned, columns=X.columns)
    if isinstance(y, pd.Series):
        y_cleaned = pd.Series(y_cleaned, name=y.name)
        
    if groups is not None:
        groups_arr = np.array(groups)
        groups_cleaned = groups_arr[keep_mask]
        return X_cleaned, y_cleaned, groups_cleaned
        
    return X_cleaned, y_cleaned


def smote_tomek(X, y, groups, target_ratio=1.0, k_neighbors=5, random_state=42):
    """
    Combines SMOTE oversampling with Tomek Links undersampling to balance and clean decision boundaries.
    """
    X_sm, y_sm, g_sm = simple_smote(
        X, y, groups, target_ratio=target_ratio, k_neighbors=k_neighbors, random_state=random_state
    )
    X_res, y_res, g_res = remove_tomek_links(X_sm, y_sm, g_sm)
    return X_res, y_res, g_res
